version: 2.1

jobs:
 build:
  docker:
    - image: circleci/openjdk:11

  steps:
    - checkout
    - run:
       name: Build Java Application
       command: |
         # build command
         ./mvnw clean install